#cloud-config
package_upgrade: true
packages:
  - linux-modules-extra-azure
  - emacs
  - iperf
  - iperf3
  - net-tools
runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az login --identity
  - make dpdk -C ${GitRepoDeployPath}/DPDK
  - make docker-compose -C ${GitRepoDeployPath}/Docker
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
